python/Django/grocery_list/grocery_list/urls.py
URLfrom django.urls import path

from . import views

app_name = 'grocery_list'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>/incomplete/', views.incomplete, name='incomplete'),
    path('<int:item_id>/complete/', views.complete, name='complete'),
    path('<int:item_id>/delete/', views.delete, name='delete'),
    path('<add/', views.add, name='add')
]

python/Django/grocery_list/grocery_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('grocery_list/', include('grocery_list.urls')),
]

python/Django/grocery_list/grocery_list/models.py
import datetime


from django.db import models
from django.utils import timezone


class GroceryItem(models.Model):
    item_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField()
    completed_date = models.DateTimeField(blank = True, null = True)
    completed_check = models.BooleanField()

    def __str__(self):
        return self.item_text

python/Django/grocery_list/grocery_list/views.py
from django.utils import timezone

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from grocery_list.models import GroceryItem


def index(request):
    latest_grocery_list = GroceryItem.objects.filter(pub_date__lte = timezone.now()).order_by('pub_date')
    return render(request, "grocery_list/index.html", {'latest_grocery_list': latest_grocery_list})

def complete(request, item_id):
    item = get_object_or_404(GroceryItem.objects.filter(pk= item_id))
    # complete = item.get(pk=request.POST['groceryitem'])
    item.completed_check = True
    item.completed_date = timezone.now()
    item.save()
    return HttpResponseRedirect(reverse('grocery_list:index'))

def incomplete(request, item_id):
    item = get_object_or_404(GroceryItem.objects.filter(pk= item_id))
    item.completed_check = False
    item.completed_date = None
    item.save()
    return HttpResponseRedirect(reverse('grocery_list:index')) 

def delete(request, item_id):
    item = get_object_or_404(GroceryItem.objects.filter(pk= item_id))
    item.delete()
    return HttpResponseRedirect(reverse('grocery_list:index'))

def add(request):
    new_item = request.POST['new_item']
    if len(new_item) > 0:
        n_item = GroceryItem(item_text=new_item, pub_date = timezone.now(), completed_date = None, completed_check = False)
        n_item.save()
    return HttpResponseRedirect(reverse('grocery_list:index'))

python/Django/grocery_list/grocery_list/templates/grocery_list/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css">
    <title>Grocery List</title>
</head>
<body>
        
        <fieldset>
            <legend><h1>Grocery List</h1></legend>
            {% if latest_grocery_list %}
                {% for item in latest_grocery_list %}
                    {% if item.completed_check == False %}
                        <h3>{{ item.item_text }}</h3>
                    {% else %}
                        <h3><s>{{ item.item_text }}</s></h3>
                    {% endif %}
                    {% comment %} <input type="checkbox" name="complete" value="{{ item.id }}" id="{{ item.id }}"> {% endcomment %}
                    {% comment %} <label for="{{item.id}}">{{ item.item_text }}</label><br> {% endcomment %}
                <form action="{% url 'grocery_list:complete' item.id %}" method = "post">
                    {% csrf_token %}
                    <input type="submit" value="Complete">
                </form>
                <form action="{% url 'grocery_list:incomplete' item.id %}" method = "post">
                    {% csrf_token %}
                    <input type="submit" value="Incomplete">
                </form>
                <form action="{% url 'grocery_list:delete' item.id %}" method = "post">
                    {% csrf_token %}
                    <input type="submit" value="Delete">
                </form>
                {% endfor %}
            {% else %}
                <p>All caught up! Add more to list when you run out of something</p>
            {% endif %}
        </fieldset>
        <fieldset>
            <legend><h2>Add item</h2></legend>
            <form action="{% url 'grocery_list:add' %}" method = "post">
                {% csrf_token %}
                <input type="text", name="new_item", id="new_item", placeholder='Enter New Item'><br>
                <input type="submit", value="Add Item">
            </form>
</body>
</html>

{% comment %} {% for choice in question.choices.all %}
    <input type="radio" name="choice" value="{{ choice.id }}" id="choice{{ forloop.counter }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %} {% endcomment %}