python/Django/URL_shortener/URL_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('short/', include('short.urls'))
]

python/Django/URL_shortener/short/urls.py
from django.urls import path
from . import views

app_name = 'short' # for namespacing

urlpatterns = [
    path('', views.index, name='index'),
    path('short/submit/', views.submit, name='submit'),
    path('<str:code>/', views.code, name='code'),
]

python/Django/URL_shortener/short/models.py
from django.db import models

class Switch(models.Model):
    long_url = models.URLField()
    code = models.CharField(max_length = 10)

    def __str__(self):
        return self.long_url

python/Django/URL_shortener/short/views.py
import imp
import re
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from.models import Switch

import random
import string

def index(request):
    # url_list = Switch.objects
    return render(request, 'short/index.html')

def submit(request):
    new_url = request.POST['long_url']
    code = ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))
    if len(new_url) > 0:
        n_url = Switch(long_url = new_url, code = code)
        n_url.save()
    return render(request, 'short/index.html', {'n_url':n_url})
    
    
def code(request, code):
    redirect = get_object_or_404(Switch, code = code)
    url = redirect.long_url
    return HttpResponseRedirect(url)

python/Django/URL_shortener/short/templates/short/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css">
    <link type="text/css" rel="stylesheet" href="{% static 'short/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'short/style.css' %}">
    <title>Document</title>
</head>
<body>
    <main class='main_field'>
        <h1> URL Shortener </h1>
        <div class='row'>
            <form class='col s12' action="{% url 'short:submit' %}" method = "post">
                <div class='row'>
                    <div class='input-field'>
                        {% csrf_token %}
                        <i class="material-icons prefix">transform</i>
                        <input id='icon_prefix2' type="url", name="long_url", id="long_url", placeholder="Enter url"><br>
                        <input type='submit', value="Switch">
                    </div>
                </div>
            </form>
        </div><br>
        <div class="switch">
            {% if n_url %}
                <p> Shortened url:<br>
                <a href="http://localhost:8000/short/{{ n_url.code }}">http://localhost:8000/short/{{ n_url.code }}</a>
                </p>
            {% endif %}
        </div>
        <script type="text/javascript" src="{% static 'short/materialize.js' %}"></script>
        <footer>
            <p>Copyright &copy; Alden Addor 2022</p>
        </footer>
    </main>
</body>
</html>