python/Django/chirp/chirp_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]

python/Django/chirp/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name="index"),
    # path('', views.PostListView.as_view(), name='index')
    path('add/', views.new_post, name='add')
]

python/Django/chirp/users/urls.py
import imp
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('<str:username>/', views.user_profile, name='profile')
]

python/Django/chirp/posts/models.py
from django.db import models
from django.utils import timezone

class Posts(models.Model):
    post = models.CharField(max_length=128)
    pub_date = models.DateTimeField(auto_now_add = True)
    author = models.ForeignKey('auth.User', related_name="posts", on_delete=models.CASCADE)

    def __str__(self):
        return self.post

    class Meta:
        ordering = ['-pub_date']

python/Django/chirp/users/models.py
from django.db import models

# Create your models here.

python/Django/chirp/posts/views.py
from django.views.generic import ListView
from time import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponseRedirect
from django.urls import reverse

from .models import Posts

# class PostListView(ListView):
#     model = Posts
#     template_name = 'index.html'

def index(request):
    posts = Posts.objects.all()
    context = {
        'post_list': posts
    }
    return render(request, 'index.html', context)

def new_post(request):
    if request.user.is_authenticated == True:
        posts = request.POST['post']
        Posts.objects.create(post = posts, author = request.user)
        return HttpResponseRedirect(reverse('posts:index'))
    else:
        return HttpResponseRedirect(reverse('login'))
    

python/Django/chirp/users/views.py
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User

class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('login')

def user_profile(request, username):
    user_profile = get_object_or_404(User, username = username)
    context = {'user_profile': user_profile}
    return render(request, 'user_profile.html', context)

python/Django/chirp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <title>CHIRP</title>
</head>
<body>
    <header class='row'>
        <h1 class='col s6'><a href="{% url 'posts:index' %}">Chirp</a></h1>
            <div class='col s6'>
                <div class='nav'>
                    {% if user.is_authenticated %}
                        <p>Greetings, <a href="{% url 'users:profile' user.username %}" >{{ user.username }}</a><br>
                        <a href="{% url 'logout' %}">Logout</a></p>
                    {% else %}
                        <a href="{% url 'login' %}">Login</a>
                        <a href="{% url 'users:signup' %}">Sign Up!</a>
                    {% endif %}
                </div>
            </div>
    </header>
    {% comment %} <div class='content'> {% endcomment %}
        <div>
            {% block content %}
            {%  endblock content %}\
        </div>
    {% comment %} <div> {% endcomment %}
        <script type="text/javascript" src="{% static 'css/materialize.js' %}"></script>
</body>
</html>

python/Django/chirp/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class='form'>
    <h3>Make Posts</h3>
    <form action="{% url 'posts:add' %}" method="post">
        {% csrf_token %}
        <input type='text' name='post'>
        <input type='submit' value='Post'>
    </form>
</div>
    {% comment %} {% if user.is_authenticated %}
        Hello {{user.username}}
    {% endif %} {% endcomment %}
<div class='content'>
    <div  class='posts'>
    {% for post in post_list %}
        <h4><a href="{% url 'users:profile' post.author.username %}" >{{ post.author.username }}</a></h4>{{post.pub_date}}
        <p>{{ post.post }}</p>
    {% endfor %}
    </div>
</div>

{% endblock content %}

python/Django/chirp/templates/signup.html
{% extends 'base.html' %}

{% block content %}

    <h1>Welcome</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign up">
    </form>

{% endblock content%}

python/Django/chirp/templates/user_profile.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ user_profile.username }}</h1>
    <h5><em>Member since {{ user_profile.date_joined }}!</em></h5>

    {% for post in user_profile.posts.all %}
            
            <p>{{post.pub_date }}<br>{{ post.post }}</p>

    {% endfor %}

{% endblock content %}